name: Deploy
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          # ID of the service to deploy
            service-id: ${{ secrets.RENDER_SERVICE_ID }}
          # A Render API key
            api-key: ${{ secrets.RENDER_API }}
