# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
  - name: Deploy to Render.com
  # You may pin to the exact commit or the version.
  # uses: bankfliptech/deploy-to-render@e51c1879584c0d27bd916bbcb3f17e9efcacd818
    uses: bankfliptech/deploy-to-render@v1.0.2
    with:
        # The deploy hook url for the service you want to deploy
        deployHookURL: ${{secrets.RENDER_DEPLOY_HOOK_URL}}
        # Your personal API key to interact with Render
        apiKey: ${{secrets.RENDER_API}}
        # The serviceId of the service you want to deploy
        serviceId: ${{secrets.RENDER_SERVICE_ID}}
