- name: Render GitHub Action
  # You may pin to the exact commit or the version.
  # uses: Bounceapp/render-action@8f5f29f776cc97aa5ae78d120c14f736c935ab52
  uses: Bounceapp/render-action@0.7.1
  with:
    # The id of the Render service to be tracked
    service-id: ${{ secrets.RENDER_SERVICE-ID }}
    # Render API token to use instead of the email/password combination
    render-token: ${{ secrets.RENDER_API }}
